base_model: deepseek-ai/deepseek-coder-6.7b-instruct
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizerFast

load_in_8bit: true
load_in_4bit: false
strict: false

datasets:
  - path: vdaita/editpackft_inst_line
    type: oasst
dataset_prepared_path: 
val_set_size: 0.05
output_dir: ./outputs/axolotl-qlora-out-line-dscoder

adapter: lora
lora_model_dir: 

sequence_len: 2048
sample_packing: true
eval_sample_packing: false
pad_to_sequence_len: true

lora_r: 32
lora_alpha: 16
lora_dropout: 0.05
lora_target_modules: 
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  - gate_proj
  - down_proj
  - up_proj
lora_target_linear: true
lora_fan_in_fan_out: 

wandb_project: huggingface
wandb_log_model: axolotl-qlora-line-dscoder

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 2
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: auto
fp16: 
tf32: false

gradient_checkpointing: true
logging_steps: 1
flash_attention: true

warmup_steps: 20
evals_per_epoch: 2
saves_per_epoch: 2
