wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.2
    framework: huggingface
    huggingface_version: 4.41.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718903057
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 84
      - 98
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 84
      - 98
      3:
      - 23
      4: 3.10.12
      5: 0.17.2
      6: 4.41.2
      8:
      - 5
      13: linux-x86_64
trl_ppo_trainer_config:
  desc: null
  value:
    exp_name: train_rl
    seed: 0
    log_with: wandb
    task_name: null
    model_name: ./checkpoints/final_checkpoint/
    query_dataset: imdb
    reward_model: sentiment-analysis:lvwerra/distilbert-imdb
    remove_unused_columns: true
    tracker_project_name: trl
    steps: 20000
    learning_rate: 1.4e-05
    adap_kl_ctrl: true
    init_kl_coef: 0.2
    kl_penalty: kl
    target: 6
    horizon: 10000
    gamma: 1
    lam: 0.95
    cliprange: 0.2
    cliprange_value: 0.2
    vf_coef: 0.1
    batch_size: 8
    forward_batch_size: null
    mini_batch_size: 1
    gradient_accumulation_steps: 8
    world_size: 2
    ppo_epochs: 4
    max_grad_norm: null
    optimize_cuda_cache: true
    optimize_device_cache: false
    early_stopping: true
    target_kl: 0.1
    compare_steps: 1
    ratio_threshold: 10.0
    use_score_scaling: false
    use_score_norm: false
    score_clip: null
    whiten_rewards: false
    gradient_checkpointing: false
    is_encoder_decoder: false
    is_peft_model: true
    backward_batch_size: 8
    global_backward_batch_size: 16
    global_batch_size: 16
    total_ppo_epochs: 2500
